server:
  port: 8080

spring:
  mail:
#    host: mail.ahzoo.cn
    host: { 邮箱域名 }
    username: { 邮箱名 }
    password: { 邮箱密码 }
#    port: 465
    port: { 邮箱端口 }
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          socketFactoryPort: { 邮箱端口 }
        # 是否开启ssl
          ssl:
            trust: "*"
            enable: true
          starttls:
            enable: true
          auth: true
        debug: true

  datasource:
    #    url: jdbc:mysql://localhost:3306/blog_z2
    url: jdbc:mysql://{ 数据库地址 }:{ 数据库端口 }/{ 数据库名 }
    username: { 用户名 }
    password: { 密码 }
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #  tomcat开启虚拟线程
  threads:
    virtual:
      enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: ahzoo-token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

author:
  mail:
    enable: true
    mine: { 本人邮件 }
    sender: { 邮件发送邮箱 }

config:
  seed: 1234567

springdoc:
  swagger-ui:
    enabled: true
