server:
  port: 8080

spring:
  mail:
#    host: mail.ahzoo.cn
    host: { 邮箱域名 }
    username: { 邮箱账户 }
    password: { 邮箱密码 }
#    port: 465
    port: { 邮箱端口 }
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          socketFactoryPort: { 邮箱端口 }
        # 是否开启ssl
          ssl:
            trust: "*"
            enable: true
          starttls:
            enable: true
          auth: true
        debug: true

  datasource:
    #    url: jdbc:mysql://localhost:3306/blog_z2
    url: jdbc:mysql://{ 数据库地址 }:{ 数据库端口 }/{ 数据库名 }
    username: { 用户名 }
    password: { 密码 }
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #  tomcat开启虚拟线程
  threads:
    virtual:
      enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  token-name: ahzoo-token
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true

author:
  mail:
    enable: true
    mine: { 本人邮箱账户 }
    sender: { 用于发送邮件的账户 }

config:
  seed: 1234567

springdoc:
  swagger-ui:
    enabled: true
