server:
  port: 8090

spring:
  mail:
    host: { 邮件发送域名 }
    username: { 邮箱地址 }
    password: { 密码 }
    port: { 邮件发送端口号 }
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          socketFactoryPort: { 邮件发送端口号 }
          ssl:
            trust: "*"
            enable: true
          starttls:
            enable: true
          auth: true
        debug: true
  datasource:
    #    url: jdbc:mysql://localhost:3306/blog_z2
    url: jdbc:mysql://{ 数据库地址 }:{ 数据库端口 }/{ 数据库名 }
    username: { 用户名 }
    password: { 密码 }
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      #      host: localhost
      host: { redis地址 }
      port: { redis端口 }
      password: { redis密码 }
  cache:
    redis:
      # 缓存过期时间：1天
      time-to-live: 86400000
  cloud:
    openfeign:
      client:
        config:
          # 全局设置
          default:
            connect-timeout: 30000
            read-timeout: 30000
      compression:
        # 开启请求压缩
        request:
          enabled: true
          mime-types: [ "text/xml", "application/xml", "application/json", "video/mp4", "text/plain" ]
          min-request-size: 102400
        # 开启响应压缩
        response:
          enabled: true
    nacos:
      discovery:
        #        server-addr: localhost:8848
        server-addr: { nacos地址 }:{ nacos端口 }
        username: { nacos用户名 }
        password: { nacos密码 }
        ephemeral: false
  #  tomcat开启虚拟线程
  threads:
    virtual:
      enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

author:
  mail:
    enable: true
    mine: { 本人邮件 }
    sender: { 邮件发送邮箱 }
